#Requires -Version 7
<#
.SYNOPSIS
    End-to-end test for .config/wezterm/mux-sessions.lua reboot persistence.

.DESCRIPTION
    Boots an isolated wezterm-mux-server (own socket, own state file, short
    save interval), builds a distinctive layout (splits, cwds, tab title,
    zoom), waits for a periodic save, hard-kills the server to simulate a
    reboot, restarts it, and asserts the layout was restored.

    The live mux server and its state file are never touched.

.EXAMPLE
    pwsh -File scripts\test-mux-sessions.ps1
#>

$ErrorActionPreference = 'Stop'
$REPO = (Split-Path $PSScriptRoot -Parent) -replace '\\', '/'
$muxExe = "$env:ProgramFiles\WezTerm\wezterm-mux-server.exe"

if (-not (Test-Path $muxExe)) {
    Write-Host "SKIP: wezterm-mux-server.exe not found" -ForegroundColor Yellow
    exit 0
}

$dir = Join-Path ([System.IO.Path]::GetTempPath()) "wezmux-e2e-$PID"
New-Item -ItemType Directory -Path $dir -Force | Out-Null
$failures = [System.Collections.Generic.List[string]]::new()
$serverProc = $null

function Assert-True([bool]$Condition, [string]$What) {
    if ($Condition) {
        Write-Host "  [ok] $What" -ForegroundColor Green
    } else {
        Write-Host "  [FAIL] $What" -ForegroundColor Red
        $script:failures.Add($What)
    }
}

function Start-TestServer {
    $env:WEZMUX_E2E_SOCK = "$dir\sock"
    $env:WEZTERM_MUX_STATE_FILE = "$dir\state.json"
    $env:WEZTERM_MUX_SAVE_INTERVAL = '5'
    $env:WEZTERM_UNIX_SOCKET = "$dir\sock"
    Remove-Item "$dir\sock" -Force -ErrorAction SilentlyContinue
    $proc = Start-Process -FilePath $muxExe -ArgumentList '--config-file', "$dir\e2e.lua" `
        -RedirectStandardError "$dir\server-$(Get-Random).log" -PassThru -WindowStyle Hidden
    Start-Sleep -Seconds 3
    if ($proc.HasExited) { throw "test mux server exited immediately" }
    return $proc
}

try {
    @"
-- Generated by scripts/test-mux-sessions.ps1: isolated server for the
-- mux-sessions.lua end-to-end test.
package.path = '$REPO/.config/wezterm/?.lua;' .. package.path
local wezterm = require('wezterm')
local config = wezterm.config_builder()
config.unix_domains = { { name = 'e2e', socket_path = os.getenv('WEZMUX_E2E_SOCK') } }
config.default_prog = { 'pwsh.exe', '-NoLogo' }
require('mux-sessions').enable()
return config
"@ | Set-Content "$dir\e2e.lua"

    Write-Host "mux-sessions e2e: building layout in isolated server" -ForegroundColor Cyan
    $serverProc = Start-TestServer

    # Pane 0 exists (default program). Build: 0 | 1 vertical cut, 0 / 2
    # horizontal cut, plus tab title and a zoomed pane.
    wezterm cli split-pane --pane-id 0 --right --percent 40 --cwd C:\Programming | Out-Null
    wezterm cli split-pane --pane-id 0 --bottom --percent 30 --cwd C:\temp | Out-Null
    wezterm cli set-tab-title --tab-id 0 'e2e-tab'
    wezterm cli activate-pane --pane-id 2
    wezterm cli zoom-pane --pane-id 2 --zoom

    Write-Host "mux-sessions e2e: waiting for periodic save" -ForegroundColor Cyan
    Start-Sleep -Seconds 8
    Assert-True (Test-Path "$dir\state.json") "state file written by periodic save"
    $state = Get-Content "$dir\state.json" -Raw | ConvertFrom-Json
    $panes = $state.windows[0].tabs[0].panes
    Assert-True ($panes.Count -eq 3) "snapshot has 3 panes (got $($panes.Count))"
    Assert-True ($state.windows[0].tabs[0].title -eq 'e2e-tab') "snapshot keeps explicit tab title"
    Assert-True (($panes | Where-Object is_zoomed).Count -eq 1) "snapshot records zoomed pane"

    Write-Host "mux-sessions e2e: simulating reboot (hard kill + restart)" -ForegroundColor Cyan
    Stop-Process -Id $serverProc.Id -Force
    Start-Sleep -Seconds 1
    $serverProc = Start-TestServer
    Start-Sleep -Seconds 2

    $restored = wezterm cli list --format json | ConvertFrom-Json
    Assert-True ($restored.Count -eq 3) "restored 3 panes (got $($restored.Count))"
    Assert-True (($restored | Where-Object tab_title -eq 'e2e-tab').Count -eq 3) "restored tab title"
    $cwds = $restored.cwd -join ' '
    foreach ($expect in 'C:/Programming/', 'C:/temp/') {
        Assert-True ($cwds -like "*$expect*") "restored pane cwd $expect"
    }
    Assert-True (($restored | Where-Object is_zoomed).Count -eq 1) "restored zoomed pane"
    $active = $restored | Where-Object { $_.is_active -and $_.cwd -eq 'file:///C:/temp/' }
    Assert-True ($null -ne $active) "restored active pane (C:/temp)"
} finally {
    if ($serverProc -and -not $serverProc.HasExited) {
        Stop-Process -Id $serverProc.Id -Force -ErrorAction SilentlyContinue
    }
    Remove-Item $dir -Recurse -Force -ErrorAction SilentlyContinue
    Remove-Item Env:\WEZTERM_UNIX_SOCKET, Env:\WEZTERM_MUX_STATE_FILE, Env:\WEZTERM_MUX_SAVE_INTERVAL, Env:\WEZMUX_E2E_SOCK -ErrorAction SilentlyContinue
}

Write-Host ""
if ($failures.Count -gt 0) {
    Write-Host "mux-sessions e2e: FAILED ($($failures.Count) assertion(s))" -ForegroundColor Red
    exit 1
}
Write-Host "mux-sessions e2e: PASS" -ForegroundColor Green
exit 0
